# -*- coding: utf-8 -*-
"""expo_game

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvPDcxU8Uhhrns3nOuUU-qi90ckYlGxk
"""

# User class to store user information
class User:
    def __init__(self, username, password):
        self.username = username
        self.password = password
        self.account_balance = 0

# Function to handle the login process
def login():
    choice = input("Do you have an account? (y/n): ")
    if choice.lower() == "y":
        username = input("Enter your username: ")
        password = input("Enter your password: ")
        return User(username, password)
    else:
        print("Please create an account.")
        return None

# Function to handle the friend invitation process
def invite_friends(user):
    choice = input("Do you prefer to play with friends? (y/n): ")
    if choice.lower() == "y":
        friend1 = input("Enter friend 1's username: ")
        friend2 = input("Enter friend 2's username: ")
        print(f"Welcome, {friend1} and {friend2}!")
        user.account_balance += 100
    else:
        print("Welcome!")
        user.account_balance += 100

# Function to handle the learn financial literacy process
def learn_financial_literacy():
    print("Learn financial literacy.")

# Function to handle the eat task
def eat_task(user):
    print("Eat Task")
    choice = input("Where do you want to eat? (1. Restaurant / 2. Home): ")
    if choice == "1":
        user.account_balance -= 20
        print("You ate at a restaurant and spent $20.")
    elif choice == "2":
        user.account_balance -= 10
        print("You ate at home and saved $10.")
    else:
        print("Invalid choice.")

# Function to handle the buy clothes task
def buy_clothes_task(user):
    print("Buy Clothes Task")
    choice = input("What type of clothes do you want to buy? (1. Designer / 2. Unbranded): ")
    if choice == "1":
        user.account_balance -= 30
        print("You bought designer clothes.")
    elif choice == "2":
        user.account_balance -= 15
        print("You bought unbranded clothes and saved $15.")
    else:
        print("Invalid choice.")

# Function to handle the rent or gamble task
def rent_or_gamble_task(user):
    print("Rent or Gamble Task")
    choice = input("What do you want to do? (1. Pay rent / 2. Gamble): ")
    if choice == "1":
        user.account_balance -= 40
        print("You paid the rent.")
    elif choice == "2":
        user.account_balance -= 40
        print("You gambled and lost $40.")
    else:
        print("Invalid choice.")

# Function to handle the game
def play_game():
    print("Embark on the journey in Prospera.")
    user = login()
    if user is None:
        return
    invite_friends(user)
    learn_financial_literacy()
    eat_task(user)
    buy_clothes_task(user)
    rent_or_gamble_task(user)
    if user.account_balance > 20:
        print("Congratulations! You have qualified for the next level.")
    elif user.account_balance < 15:
        print("Game Over")

# Run the game
if __name__ == "__main__":
    play_game()